name: CI for QA Python Course

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    env:
      X_API_KEY:     ${{ secrets.X_API_KEY }}
      TEST_EMAIL:    ${{ secrets.TEST_EMAIL }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check import sorting (isort)
        run: isort --check-only .

      - name: Lint with flake8
        run: flake8 .

      - name: Check formatting with Black
        run: black --check .

      - name: Run pytest (with HTML report)
        run: |
          pytest -q --disable-warnings --maxfail=1 \
                 --html=report.html --self-contained-html
        # перезапишите пути/опции pytest по необходимости

      - name: Upload pytest HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html
